Repository GDSC-CAU/GDSC-SPACE-STUDY-ASSIGNMENT-VER2, pull requests merged in 2025-02, with the labels that each got.

#18 [DEV] 메인 페이지 구현
  Taeyang/react-ts/.eslintignore
  Taeyang/react-ts/.eslintrc.cjs
  Taeyang/react-ts/.gitignore
  Taeyang/react-ts/.prettierignore
  Taeyang/react-ts/.prettierrc
  Taeyang/react-ts/index.html
  Taeyang/react-ts/package.json
  Taeyang/react-ts/pnpm-lock.yaml
  Taeyang/react-ts/postcss.config.cjs
  Taeyang/react-ts/readme.md
  Taeyang/react-ts/src/app/detail/[id]/page.tsx
  Taeyang/react-ts/src/app/emotions/[emotion]/page.tsx
  Taeyang/react-ts/src/app/emotions/page.tsx
  Taeyang/react-ts/src/app/layout.tsx
  Taeyang/react-ts/src/app/page.tsx
  Taeyang/react-ts/src/components/DiaryForm.tsx
  Taeyang/react-ts/src/components/DiaryList.tsx
  Taeyang/react-ts/src/components/Link.tsx
  Taeyang/react-ts/src/components/readme.md
  Taeyang/react-ts/src/constants/colorClasses.ts
  Taeyang/react-ts/src/constants/emotions.ts
  Taeyang/react-ts/src/constants/weathers.ts
  Taeyang/react-ts/src/interface/diary.ts
  Taeyang/react-ts/src/main.tsx
  Taeyang/react-ts/src/provider/Diary.tsx
  Taeyang/react-ts/src/router/index.tsx
  Taeyang/react-ts/src/tailwind.css
  Taeyang/react-ts/src/vite-env.d.ts
  Taeyang/react-ts/tailwind.config.js
  Taeyang/react-ts/tsconfig.json
  Taeyang/react-ts/tsconfig.node.json
  Taeyang/react-ts/vite.config.ts
Labels: dev

#14 [DEV] 다이어리 상세 페이지 구현
  YuJin/react-ts/src/app/constants/diaryInputs.ts
  YuJin/react-ts/src/app/constants/diaryOutput.ts
  YuJin/react-ts/src/app/detail/[id]/page.tsx
  YuJin/react-ts/src/app/page.tsx
  YuJin/react-ts/src/app/utils/dateFormat.ts
  YuJin/react-ts/src/components/diaryViewer/diaryViewerBox.tsx
  YuJin/react-ts/src/hooks/useLocalStorage.tsx
  YuJin/react-ts/src/interface/diaryDetail.interface.ts
  YuJin/react-ts/src/tailwind.css
  YuJin/react-ts/tailwind.config.js
Labels: dev

#19 [DEV] emotion 리스트 페이지 구현
  YuJin/react-ts/package.json
  YuJin/react-ts/pnpm-lock.yaml
  YuJin/react-ts/src/app/constants/diaryOutput.ts
  YuJin/react-ts/src/app/constants/emotions.ts
  YuJin/react-ts/src/app/emotions/page.tsx
  YuJin/react-ts/src/components/diaryViewer/diaryTable.tsx
  YuJin/react-ts/src/components/diaryViewer/diaryViewerBox.tsx
  YuJin/react-ts/src/router/index.tsx
  YuJin/react-ts/src/styles/emotionCard.ts
Labels: dev

#32 [DEV] 메인 페이지 및 상세 페이지 구현
  HeeJung/react-ts/src/app/constants/emotion.ts
  HeeJung/react-ts/src/app/constants/weather.ts
  HeeJung/react-ts/src/app/detail/[id]/page.tsx
  HeeJung/react-ts/src/app/page.tsx
Labels: dev

#37 [REFACTOR] 작은 규모의 리펙토링
  YuJin/react-ts/src/app/constants/diaryOutputs.ts
  YuJin/react-ts/src/app/constants/index.ts
  YuJin/react-ts/src/app/constants/routes.ts
  YuJin/react-ts/src/app/detail/[id]/page.tsx
  YuJin/react-ts/src/app/emotions/[emotion]/page.tsx
  YuJin/react-ts/src/app/emotions/page.tsx
  YuJin/react-ts/src/app/page.tsx
  YuJin/react-ts/src/components/diaryViewer/DiaryTable.tsx
  YuJin/react-ts/src/components/diaryViewer/diaryViewerBox.tsx
  YuJin/react-ts/src/hooks/useLocalStorage.tsx
  YuJin/react-ts/src/interface/diaryDetail.interface.ts
  YuJin/react-ts/src/router/index.tsx
Labels: refactor

#40 [FIX] 파일 이름 오류
  YuJin/react-ts/src/app/emotions/[emotion]/page.tsx
  YuJin/react-ts/src/components/diaryViewer/DiaryBar.tsx
  YuJin/react-ts/src/components/diaryViewer/DiaryTable.tsx
  YuJin/react-ts/src/components/diaryViewer/DiaryViewerBox.tsx
Labels: fix

#23 [DEV] 메인페이지, 일기 상세 페이지 구현
  Junghyun/react-ts/src/app/detail/[id]/page.tsx
  Junghyun/react-ts/src/app/page.tsx
  Junghyun/react-ts/src/components/DiaryCard.tsx
  Junghyun/react-ts/src/provider/Diary.tsx
  Junghyun/react-ts/src/tailwind.css
Labels: dev

#27 [DEV] 상세 페이지 구현
  Yewon/react-ts/src/app/detail/[id]/page.tsx
  Yewon/react-ts/src/app/page.tsx
  Yewon/react-ts/src/components/DiaryCard.tsx
  Yewon/react-ts/src/tailwind.css
  Yewon/react-ts/src/util/dateUtil.ts
Labels: dev

#36 [DEV] 감정 모아보기 & 일기 읽어보기 상세 페이지 구현
  Taeyang/react-ts/src/app/detail/[id]/page.tsx
  Taeyang/react-ts/src/app/emotions/[emotion]/page.tsx
  Taeyang/react-ts/src/constants/emotions.ts
  Taeyang/react-ts/src/main.tsx
  Taeyang/react-ts/src/provider/Diary.tsx
Labels: dev

#44 [FIX] import문 파일 이름 변경
  YuJin/react-ts/src/app/page.tsx
Labels: fix

#41 [DEV] 감정/감정 일기 모아보기, 일기 상세 페이지 구현
  SoWon/react-ts/src/app/detail/[id]/page.tsx
  SoWon/react-ts/src/app/emotions/[emotion]/page.tsx
  SoWon/react-ts/src/app/emotions/page.tsx
  SoWon/react-ts/src/app/page.tsx
  SoWon/react-ts/src/components/Button.tsx
  SoWon/react-ts/src/components/diary/Card.tsx
  SoWon/react-ts/src/constants/index.ts
  SoWon/react-ts/src/style/config.ts
  SoWon/react-ts/src/tailwind.css
  SoWon/react-ts/src/utils/formatDate.ts
Labels: dev
